import FePage from "../components/fe-pages/fe-page";
import FeHeader from "../components/fe-header/fe-header";
import FeFooter from "../components/fe-footer/fe-footer";
import FeReplaceDataWithPlaceholder from "../components/fe-replace-data-with-placeholder/fe-replace-data-with-placeholder";
import FeMembershipDashboardButton from "../components/fe-membership-dashboard-button/fe-membership-dashboard-button";
import "./main.scss";
new FePage();
new FeHeader();
new FeFooter();
new FeMembershipDashboardButton();
new FeReplaceDataWithPlaceholder();