pipeline {
  agent {
    kubernetes {
      cloud 'fngn-k8s-core-west-1'
      yaml libraryResource ('agents/java11.yaml')
    }
  }
  options {
    buildDiscarder(logRotator(artifactDaysToKeepStr: '', artifactNumToKeepStr: '5', daysToKeepStr: '', numToKeepStr: '5'))
    timeout(time: 15, unit: 'MINUTES')
    // This is required if you want to clean before build
    skipDefaultCheckout(true)
  }
  environment {
    project = "aem"
    emailRecipients = "cfoon@edelmanfinancialengines.com"
  }
  properties([gitLabConnection('GitlabProd')])
  stages {
    stage ('Setup') {
      when { anyOf { branch 'main'; branch 'develop' } }
      steps {
        // Clean dir before build
        cleanWs(
          deleteDirs: true
        )
        checkout scm
      }
    }
    stage ('Checkmarx SCA') {
      when { anyOf { branch 'main'; branch 'develop' } }
      steps {
        echo "run checkmarxSCA placeholder"
      }
    }
    stage ('Checkmarx SAST') {
      when { anyOf { branch 'main'; branch 'develop' } }
      steps {
        echo "run checkmarxSAST placeholder"
      }
    }
    stage ('Adobe Sync') {
      environment {
        AEM_SYNC_USER_NAME = "cfoon-edelman-financial-engines-com"
        AEM_SYNC_USER_ACCESS_TOKEN = credentials('jenkins/aem-sync-user-access-token-tmp')
      }
      when { anyOf { branch 'main'; branch 'develop' } }
      steps {
        echo "Sync the env.gitlabSourceBranch branch to Adobe Git"
        sh "#!/bin/bash \n" +
           "git remote add sync https://$AEM_SYNC_USER_NAME:$AEM_SYNC_USER_ACCESS_TOKEN@git.cloudmanager.adobe.com/financialengines/FinancialEnginesSites-p91602-uk32541/; \n"
        // "git checkout env.gitlabSourceBranch; \n" +
        // "git pull; \n" +   
        // "git push sync env.gitlabSourceBranch \n"
      }
    }
  }
}
